### ISSUE TITLE
Malware and virus anyone?

### ISSUE THREAD

**Issue by mountaincoder** [fiveseven808/AmazonDashButtonHack#1]

**Comment by fiveseven808** [comment]
Written in AHK, run it through virustotal, shouldn't come up with anything. Source should be going up today.

**Comment by fiveseven808** [comment]
Source files uploaded for latest discovery program and button daemon. You're welcome to review the code and close this issue if it appeases you ;)

**Comment by mountaincoder** [comment]
Perhaps it's a false positive, but Windows Defender came back with this:

Trojan: Win32/Rundas!plock
file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{265A0DAA-F995-49A1-A658-144AF0830A66}-AmazonDashButtonHack-master.zip->AmazonDashButtonHack-master/bin/AmazonButton_Discovery.exe
file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{265A0DAA-F995-49A1-A658-144AF0830A66}-AmazonDashButtonHack-master.zip->AmazonDashButtonHack-master/prod/AmazonButton_Discovery 0901 1853.zip->AmazonButton_Discovery.exe
file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\48C35CA3-E0A0-B7B9-B531-496A1695FCE6_1d1d5647ccd70ba->AmazonDashButtonHack-master/bin/AmazonButton_Discovery.exe
file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\48C35CA3-E0A0-B7B9-B531-496A1695FCE6_1d1d5647ccd70ba->AmazonDashButtonHack-master/prod/AmazonButton_Discovery 0901 1853.zip->AmazonButton_Discovery.exe
webfile:C:\ProgramData\Microsoft\Windows Defender\LocalCopy{265A0DAA-F995-49A1-A658-144AF0830A66}-AmazonDashButtonHack-master.zip|chrome.exe
webfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\48C35CA3-E0A0-B7B9-B531-496A1695FCE6_1d1d5647ccd70ba|https://codeload.github.com/fiveseven808/AmazonDashButtonHack/zip/master|chrome.exe

**Comment by fiveseven808** [comment]
https://virustotal.com/en/file/17273f7aa7a31f02e615c939066fa73f68d3d0d887884763583c410c70d0f8a2/analysis/

Well for one, apparently antiviruses can't agree on what type of virus it is lol

Quite interesting actually, my discovery program shows up at 5/54
https://virustotal.com/en/file/4261fec83ab933244866e7a207afdf6cbdbc9e46729eb085fe07dae080fd88db/analysis/

While the daemon gets a 3/54
https://virustotal.com/en/file/7c8c253f44198b21cc57ec2ea8a976c2d12929c7db09e0baa0a5b55f286c5f89/analysis/

Again, make your own decision lol 
Since I posted the code, you're welcome to compile it and run it yourself ;)

**Comment by fiveseven808** [comment]
https://virustotal.com/en/file/5c599d26ec437b5727c9078ba1b0c9fd6df0fc9702fe07634500f80d90184508/analysis/1467533136/

3/52 for my latest build. Try it and let me know how it goes!
